/**
 * worldmap.js — the Earth's map, painted onto whatever surface is on screen.
 *
 * Every flat map of the world is a lie of a particular shape. Mercator makes
 * Greenland the size of Africa; equal-area projections buy that back by
 * shearing everything; and no projection escapes, because a sphere has
 * curvature and a sheet of paper does not — that is Gauss's Theorema Egregium,
 * and it is the one theorem in this whole program that a student is most
 * likely to have heard of and least likely to have seen.
 *
 * So: take the map that lives on the rectangle — plate carrée, longitude across
 * and latitude up, the most naive projection there is — and lay it on the
 * surface. On the standard sphere it comes back to being the globe it was
 * traced from, and the distortion visibly *un*-happens: Greenland shrinks,
 * Antarctica stops being a continent-wide smear. On a torus, a saddle or a
 * hillside, it distorts in a way that is that surface's own. Putting the same
 * rectangle onto several surfaces one after another is as direct a look at
 * curvature as this program can offer.
 *
 * Where the rectangle goes, per kind of surface:
 *
 *   parametric  the parameter rectangle. This is the honest answer for a
 *       parametrised surface — it is the same rectangle the surface was built
 *       from — and it is why the usual sphere reproduces the globe exactly.
 *
 *   graph       the domain. The map is laid on the (x, y) rectangle and lifted
 *       to z = f(x,y), so mountains push the continents apart.
 *
 *   implicit    there is no rectangle, so one is made: longitude and latitude
 *       about the surface's own centre. On F = x²+y²+z²−1 that is again the
 *       globe; on anything else it is the shadow the globe casts on it.
 *
 * The coastlines are in worldmap-data.js — 1400-odd closed rings of Natural
 * Earth's land polygons, generated by tools/build-worldmap.mjs and carried in
 * the bundle, because a page opened from a memory stick has no network.
 */

import * as THREE from '../vendor/three.module.js';
import { RINGS } from './worldmap-data.js';

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const VALUE = (() => {
  const v = new Int8Array(128).fill(-1);
  for (let i = 0; i < ALPHABET.length; i++) v[ALPHABET.charCodeAt(i)] = i;
  return v;
})();

/**
 * One encoded ring, back to [lon, lat, lon, lat, …] in degrees.
 *
 * The mirror of the encoder: base-64 varints, five bits to a character with the
 * sixth as the continuation flag, zigzagged so a small negative step is a small
 * number, and delta-coded along the ring.
 */
function decodeRing(s) {
  const out = [];
  let i = 0, x = 0, y = 0;
  while (i < s.length) {
    for (let which = 0; which < 2; which++) {
      let z = 0, shift = 1, c;
      do {
        c = VALUE[s.charCodeAt(i++)];
        z += (c & 31) * shift;
        shift *= 32;
      } while (c & 32);
      const d = (z & 1) ? -(z + 1) / 2 : z / 2;
      if (which === 0) x += d; else y += d;
    }
    out.push(x / 100, y / 100);
  }
  return out;
}

let decoded = null;
function coastlines() {
  if (!decoded) decoded = RINGS.map(decodeRing);
  return decoded;
}

/* ------------------------------------------------------------ the image */

const WIDTH = 2048;                 // 0.176° per pixel: finer than the data
const HEIGHT = 1024;

const OCEAN = '#1b4c74';
const LAND = '#5c8f4a';
const COAST = '#24402a';
const GRID = 'rgba(255,255,255,0.20)';
const AXIS = 'rgba(255,255,255,0.45)';

let texture = null;

/**
 * The map itself, drawn once and kept.
 *
 * Plate carrée: x is longitude, y is latitude, both linear. Every distortion
 * the student is about to see belongs to the surface it is laid on, not to the
 * map — which is the point, so the map has to be the simple one.
 */
export function worldTexture() {
  if (texture) return texture;

  const canvas = document.createElement('canvas');
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
  const g = canvas.getContext('2d');

  g.fillStyle = OCEAN;
  g.fillRect(0, 0, WIDTH, HEIGHT);

  const X = (lon) => ((lon + 180) / 360) * WIDTH;
  const Y = (lat) => ((90 - lat) / 180) * HEIGHT;

  // All rings in one path, filled with the even-odd rule: a hole inside a
  // landmass is then water, which is what a hole in a land polygon means.
  g.beginPath();
  for (const r of coastlines()) {
    g.moveTo(X(r[0]), Y(r[1]));
    for (let i = 2; i < r.length; i += 2) g.lineTo(X(r[i]), Y(r[i + 1]));
    g.closePath();
  }
  g.fillStyle = LAND;
  g.fill('evenodd');
  g.strokeStyle = COAST;
  g.lineWidth = 1.2;
  g.stroke();

  // The graticule, because the distortion is only legible against a grid that
  // is known to be regular. Every 30°, with the equator and the prime meridian
  // picked out.
  g.lineWidth = 1;
  for (let lon = -180; lon <= 180; lon += 30) {
    g.strokeStyle = lon === 0 ? AXIS : GRID;
    g.beginPath();
    g.moveTo(X(lon), 0);
    g.lineTo(X(lon), HEIGHT);
    g.stroke();
  }
  for (let lat = -60; lat <= 60; lat += 30) {
    g.strokeStyle = lat === 0 ? AXIS : GRID;
    g.beginPath();
    g.moveTo(0, Y(lat));
    g.lineTo(WIDTH, Y(lat));
    g.stroke();
  }

  texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.ClampToEdgeWrapping;
  texture.anisotropy = 8;
  texture.needsUpdate = true;
  return texture;
}

/* ------------------------------------------------------- where it goes */

/**
 * Write the texture coordinates that lay the map on `mesh`.
 *
 * @param kind  'graph' | 'parametric' | 'implicit'
 * @param opts  the rectangle to map from: { umin, umax, vmin, vmax } for a
 *              parametric patch, { xmin, xmax, ymin, ymax, field } for a graph,
 *              { centre } for an implicit surface.
 * @returns true if coordinates were written.
 */
export function mapUV(mesh, kind, opts = {}) {
  if (!mesh) return false;
  const geom = mesh.geometry;
  const pos = geom.getAttribute('position');
  if (!pos) return false;
  const n = pos.count;
  const uv = new Float32Array(n * 2);

  if (kind === 'parametric') {
    // The parameter rectangle, straight across. The surface keeps its raw
    // (u, v) in its uv attribute, so this is a rescaling of what is there.
    const src = geom.getAttribute('uv');
    if (!src) return false;
    const { umin = 0, umax = 1, vmin = 0, vmax = 1 } = opts;
    const du = (umax - umin) || 1;
    const dv = (vmax - vmin) || 1;
    for (let i = 0; i < n; i++) {
      uv[i * 2] = (src.getX(i) - umin) / du;
      // v runs from the top of the map down, because the usual sphere's v is
      // colatitude: v = 0 is the north pole, and the north pole belongs at the
      // top of the picture.
      uv[i * 2 + 1] = 1 - (src.getY(i) - vmin) / dv;
    }
  } else if (kind === 'graph') {
    const f = opts.field;
    if (!f) return false;
    const dx = (f.xmax - f.xmin) || 1;
    const dy = (f.ymax - f.ymin) || 1;
    for (let i = 0; i < n; i++) {
      uv[i * 2] = (f.mathX(pos.getX(i)) - f.xmin) / dx;
      uv[i * 2 + 1] = (f.mathY(pos.getZ(i)) - f.ymin) / dy;
    }
  } else {
    // Longitude and latitude about the surface's own centre. World y is up, so
    // latitude is measured from it and longitude goes round the (x, z) plane.
    const c = opts.centre || new THREE.Vector3();
    for (let i = 0; i < n; i++) {
      const x = pos.getX(i) - c.x, y = pos.getY(i) - c.y, z = pos.getZ(i) - c.z;
      const r = Math.hypot(x, y, z) || 1;
      uv[i * 2] = 0.5 + Math.atan2(z, x) / (2 * Math.PI);
      uv[i * 2 + 1] = 0.5 + Math.asin(Math.max(-1, Math.min(1, y / r))) / Math.PI;
    }
    fixSeam(geom, uv);
  }

  geom.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
  return true;
}

/**
 * Stop the meridian at ±180° from smearing the whole map across one triangle.
 *
 * A triangle straddling the date line has vertices at u ≈ 0.99 and u ≈ 0.01,
 * and the interpolator does not know they are neighbours: it runs the entire
 * map backwards across the triangle, which draws as a bright vertical scar all
 * the way round the surface. The cure is to let those coordinates run past 1
 * instead of wrapping — the texture repeats, so u = 1.01 is the same column as
 * u = 0.01 — which is only possible if the vertices belong to one triangle.
 * Marching tetrahedra produces exactly that: an unindexed soup of triangles.
 * An indexed mesh shares its vertices between triangles and cannot be fixed
 * this way, so it is left alone; the parametric and graph paths do not need it.
 */
function fixSeam(geom, uv) {
  if (geom.index) return;
  for (let t = 0; t + 2 < uv.length / 2; t += 3) {
    let lo = Infinity, hi = -Infinity;
    for (let k = 0; k < 3; k++) {
      lo = Math.min(lo, uv[(t + k) * 2]);
      hi = Math.max(hi, uv[(t + k) * 2]);
    }
    if (hi - lo <= 0.5) continue;
    for (let k = 0; k < 3; k++) {
      if (uv[(t + k) * 2] < 0.5) uv[(t + k) * 2] += 1;
    }
  }
}

/**
 * Put the map on a material, or take it off again.
 *
 * Vertex colours have to go while it is on: they multiply the texture, and the
 * terrain palette underneath would tint the Atlantic green. They come back when
 * it does.
 */
export function setMapMaterial(material, on) {
  const list = Array.isArray(material) ? material : [material];
  for (const m of list) {
    if (!m) continue;
    if (on) {
      if (m.userData.vertexColors === undefined) m.userData.vertexColors = m.vertexColors;
      // Put back whatever was on the material, not nothing.
      //
      // The world map is a *borrowed* slot: a surface may already carry a map
      // of its own — the campus does, a Sentinel-2 photograph of the ground —
      // and hanging the atlas on it and then clearing the slot on the way out
      // threw that away. It looked like the satellite drape had failed, when
      // in fact it had been unhooked by a feature that was switched off.
      if (m.userData.baseMap === undefined) m.userData.baseMap = m.map || null;
      m.map = worldTexture();
      m.vertexColors = false;
      m.color.setRGB(1, 1, 1);
    } else {
      if (m.userData.baseMap !== undefined) {
        m.map = m.userData.baseMap;
        delete m.userData.baseMap;
      }
      if (m.userData.vertexColors !== undefined) m.vertexColors = m.userData.vertexColors;
    }
    m.needsUpdate = true;
  }
}

/**
 * A seam in the wall for the checks in tools/ — the decoder, which is the one
 * piece here whose correctness is a question about data rather than about
 * pixels, and so the one piece worth testing without a browser.
 */
export const __test = { decodeRing };
