# -*- coding: utf-8 -*-
"""Spanish first-column label -> English first-column label.
Wherever the applet itself has an English name for a control, that exact
string is used, so the guide names the button the reader is looking at."""
LBL = {
# ---- Óptimo del Consumidor -------------------------------------------------
"<b>Diagrama 2D</b> · plano (x, y)": "<b>2D diagram</b> · (x, y) plane",
"<b>Superficie 3D</b> · z = u(x, y)": "<b>3D surface</b> · z = u(x, y)",
"Gasto": "Spend",
"RMS": "MRS",
"Brecha": "Gap",
"u máx.": "max u",
"<b>Explorar</b> / <b>Retos</b>": "<b>Explore</b> / <b>Challenges</b>",
"<b>Preferencias</b>": "<b>Preferences</b>",
"<b>Restricción presupuestaria</b>": "<b>Budget constraint</b>",
"<b>Método gráfico</b>": "<b>Graphical method</b>",
"<b>Capas</b>": "<b>Layers</b>",
"<b>Dominio</b>": "<b>Domain</b>",
"<b>Ajustar al presupuesto</b>": "<b>Fit to budget</b>",
"Mapa de utilidad": "Utility map",
"Curvas de fondo": "Contours",
"Curva de nivel": "Level curve",
"Curva por P": "Curve through P",
"Conjunto factible": "Feasible set",
"Corte 3D": "3D slice",
"Tangente en P": "Tangent at P",
"Gradiente": "Gradient",
"Parciales": "Partials",
"Plano de corte": "Cutting plane",
"Sólo lo asequible": "Affordable only",
"Mostrar óptimo": "Show optimum",
"Dejar rastro": "Leave a trail",
"1 · Cobb–Douglas": "1 · Cobb–Douglas",
"2 · Cobb–Douglas asimétrica": "2 · Asymmetric Cobb–Douglas",
"3 · Sustitutos perfectos": "3 · Perfect substitutes",
"4 · Complementarios perfectos": "4 · Perfect complements",
"5 · Cuasilineal": "5 · Quasilinear",
"6 · CES": "6 · CES",
"El óptimo se sale del marco": "The optimum leaves the frame",
"La superficie 3D se ve plana": "The 3D surface looks flat",
"No consigo arrastrar P": "I cannot drag P",
"La curva de indiferencia no aparece": "The indifference curve does not appear",
"Los retos están bloqueados": "The challenges are locked",
# ---- Funciones de Demanda --------------------------------------------------
"<b>Elección</b> · plano (x, y)": "<b>Choice</b> · (x, y) plane",
"<b>Demanda</b>": "<b>Demand</b>",
"Tipo": "Type",
"<b>Cobb–Douglas</b>": "<b>Cobb–Douglas</b>",
"<b>CES</b>": "<b>CES</b>",
"<b>Cuasilineal</b>": "<b>Quasilinear</b>",
"<b>Lineal (sustitutos)</b>": "<b>Linear (substitutes)</b>",
"<b>X inferior (Giffen)</b>": "<b>X inferior (Giffen)</b>",
"<b>Personalizada</b>": "<b>Custom</b>",
"<b>Variable que varía</b>": "<b>Variable being swept</b>",
"<b>Marcar al mover</b>": "<b>Mark while moving</b>",
"<b>Registrar punto</b>": "<b>Record point</b>",
"<b>Barrido</b> / <b>Parar</b>": "<b>Sweep</b> / <b>Stop</b>",
"<b>Limpiar</b>": "<b>Clear</b>",
"Puntos registrados": "Recorded points",
"Unir los puntos": "Join the points",
"Revelar la curva": "Reveal the curve",
"Senda precio-consumo": "Price-consumption path",
"Recta presupuestaria": "Budget line",
"Curva de indiferencia": "Indifference curve",
"Demanda de x": "Demand for x",
"Demanda de y": "Demand for y",
"Resaltar tramo Giffen": "Highlight Giffen stretch",
"Retícula": "Grid",
"La curva está aplastada contra el eje": "The curve is squashed against the axis",
"El eje se mueve cada vez que toco algo": "The axis moves every time I touch something",
"La casilla del número no hace nada": "The number box does nothing",
"Los puntos registrados desaparecen": "The recorded points vanish",
"No aparece la casilla para escribir φ": "The box for typing φ does not appear",
"Sale «φ sólo puede depender de x»": "It says “φ may only depend on x”",
# ---- Restricciones No Lineales ---------------------------------------------
"<b>Plano (x, y)</b>": "<b>Plane (x, y)</b>",
"<b>Utilidad sobre la restricción</b>": "<b>Utility along the constraint</b>",
"Coste": "Cost",
"Ventaja del efectivo": "Cash advantage",
"Tipo de óptimo": "Kind of optimum",
"Pendiente en x_s": "Slope at x_s",
"Salto en x_s": "Jump at x_s",
"<b>Restricción simple</b>": "<b>Simple constraint</b>",
"<b>Subsidio en especie (no excluyente)</b>": "<b>In-kind subsidy (non-exclusive)</b>",
"<b>Subsidio parcial en especie</b>": "<b>Partial in-kind subsidy</b>",
"<b>Subsidio excluyente</b>": "<b>Exclusive subsidy (public schools)</b>",
"<b>Subsidio parcial excluyente</b>": "<b>Partial exclusive subsidy</b>",
"<b>Equivalente en efectivo (total)</b>": "<b>Cash equivalent (full)</b>",
"<b>Equivalente en efectivo (parcial)</b>": "<b>Cash equivalent (partial)</b>",
"<b>Sombrear fuera del conjunto factible</b>": "<b>Shade outside the feasible set</b>",
"<b>Plano XY</b>": "<b>XY plane</b>",
"Degradado de calor": "Heat gradient",
"Curva por el óptimo": "Curve through the optimum",
"Óptimo": "Optimum",
"Vértices": "Vertices",
"Conjunto comparado": "Compared set",
"Sale «La frontera se sale del marco»": "It says “The frontier runs outside the frame”",
"Los dos esquemas se ven idénticos": "The two schemes look identical",
"La ventaja del efectivo sale cero": "The cash advantage comes out zero",
"El panel 3D va lento": "The 3D panel is slow",
"No consigo volver a la vista libre": "I cannot get back to the free view",
# ---- Impuesto a la Renta del Trabajo ---------------------------------------
"<b>Tipos marginales</b>": "<b>Marginal rates</b>",
"<b>Tipos medios</b>": "<b>Average rates</b>",
"<b>Consumo y ocio</b>": "<b>Consumption and leisure</b>",
"<b>Renta neta</b> / <b>Utilidad</b>": "<b>Net income</b> / <b>Utility</b>",
"Consumo, Trabajo L*, Ocio": "Consumption, Labour L*, Leisure",
"Renta bruta": "Gross income",
"Impuesto": "Tax",
"Tipo medio": "Average rate",
"Tipo marginal": "Marginal rate",
"Mayor salto": "Largest drop",
"Umbrales": "Thresholds",
"El óptimo sale en «No trabaja»": "The optimum comes out as “No work”",
"Los umbrales no aparecen": "The thresholds do not appear",
"No veo ninguna diferencia entre los dos modos": "I see no difference between the two modes",
"«Mayor salto» sale cero": "“Largest drop” comes out zero",
"El dibujo se ve al revés de lo que espero": "The picture is mirrored from what I expect",
# ---- Efectos Ingreso y Sustitución -----------------------------------------
"<b>Slutsky</b> — mantener la canasta": "<b>Slutsky</b> — hold the bundle",
"<b>Hicks</b> — mantener la utilidad": "<b>Hicks</b> — hold the utility",
"<b>Panel de demanda</b>": "<b>Demand panel</b>",
"Restricción inicial / compensada / final": "Original / compensated / final constraint",
"Canastas (B₀, B₁)": "Bundles (B₀, B₁)",
"Descomposición (B_S)": "Decomposition (B_S)",
"Flechas de los efectos": "Effect arrows",
"Curvas de indiferencia": "Indifference curves",
"B₀ · inicial, B<sub>S</sub> · sustitución, B₁ · final":
    "B₀ · original, B<sub>S</sub> · substitution, B₁ · final",
"Renta compensada": "Compensated income",
"Sustitución / Ingreso / Total": "Substitution / Income / Total",
"Las tres canastas coinciden": "The three bundles coincide",
"No aparece B<sub>S</sub>": "B<sub>S</sub> does not appear",
"El efecto sustitución sale positivo": "The substitution effect comes out positive",
"Sale «Algo se sale del marco»": "It says “Something runs outside the frame”",
"El panel de demanda sale a trozos": "The demand panel comes out in pieces",
"La bandera roja no sale nunca": "The red flag never appears",
}

# Labels that read the same in both languages: symbols, formulas, code and
# proper names. Listed rather than guessed, so a new Spanish label cannot slip
# into the English guide unnoticed.
NEUTRAL = {
  "x, y", "u(P)", "p<sub>x</sub>/p<sub>y</sub>",
  "x*, y*", "x*, y*, u(x*, y*)", "u(c*, ℓ*)",
  "<b>B₀</b>", "<b>B<sub>S</sub></b>", "<b>B₁</b>",
  "<b>3D</b>", "<b>X–Z</b>", "<b>X–Y</b>", "<b>Y–Z</b>",
  "<code>+ − * / ^</code>", "<code>( )</code>", "<code>sqrt ln log exp abs</code>",
  "<code>min max</code>", "<code>sin cos</code>", "<code>e pi</code>",
  "<code>2x</code>, <code>3xy</code>",
  "<code>x^0.5*y^0.5</code>", "<code>x^0.3*y^0.7</code>", "<code>x^0.7*y^0.3</code>",
  "<code>min(2x,y)</code>", "<code>min(x,y)</code>", "<code>min(x,3y)</code>",
  "<code>3x+y</code>", "<code>x+2y</code>", "<code>x+y</code>",
  "<code>4ln(x)+y</code>", "<code>4ln(x)</code>", "<code>2ln(x)+y</code>",
  "<code>ln(x)+y</code>", "<code>x+2ln(y)</code>", "<code>3ln(y)</code>",
  "<code>2sqrt(x)</code>",
  "<code>(x^0.5+y^0.5)^2</code>", "<code>(x^(-1)+y^(-1))^(-1)</code>",
}
